const meatMeals = [
  // New dishes from new_images folder
  {
    title: "Bratwurst mit Pommes",
    image: "images/bratwurst-pommes.jpeg",
    type: "meat",
    constraints: ["oven"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Bratwurst: "600g",
      "Pommes frites": "800g",
      Senf: "50ml",
      Ketchup: "50ml",
    },
  },

  {
    title: "Burger mit Pommes",
    image: "images/burger-pommes.jpeg",
    type: "meat",
    constraints: ["grain"],
    region: "north_american",
    approved: "False",
    ingredients: {
      "Hackfleisch-Patty": "800g",
      "Burger-Brötchen": "4 Stück",
      "Pommes frites": "600g",
      Käsescheiben: "200g",
      Salat: "200g",
      Tomaten: "300g",
    },
  },

  {
    title: "Butter Chicken",
    image: "images/butter-chicken.jpeg",
    type: "meat",
    constraints: ["dairy", "grain"],
    region: "south_east_asian",
    approved: "False",
    ingredients: {
      Hähnchenbrust: "800g",
      Basmatireis: "300g",
      Sahne: "300ml",
      Tomatensoße: "400ml",
      "Garam Masala": "20g",
      Ingwer: "30g",
      Knoblauch: "6 Zehen",
    },
  },

  {
    title: "Chicken Pot Pie",
    image: "images/chicken-pot-pie.jpeg",
    type: "meat",
    constraints: ["oven", "grain", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Hähnchenfleisch: "600g",
      Blätterteig: "400g",
      Mischgemüse: "500g",
      Sahne: "200ml",
      Hühnerbrühe: "300ml",
      Butter: "60g",
    },
  },

  {
    title: "Couscous Salat mit Grillfleisch",
    image: "images/couscus-salat-grillfleisch.jpeg",
    type: "meat",
    constraints: ["grain", "salad"],
    region: "middle_eastern",
    approved: "False",
    ingredients: {
      Couscous: "300g",
      Grillfleisch: "600g",
      "Gemüse gemischt": "400g",
      Olivenöl: "80ml",
      Zitrone: "2 Stück",
      Petersilie: "40g",
    },
  },

  {
    title: "Enchilada",
    image: "images/enchilada.jpeg",
    type: "meat",
    constraints: ["grain", "dairy", "oven"],
    region: "latin_american",
    approved: "False",
    ingredients: {
      Tortillas: "8 Stück",
      Hackfleisch: "500g",
      Käse: "300g",
      "Enchilada-Sauce": "400ml",
      Bohnen: "400g",
      "Saure Sahne": "200ml",
    },
  },

  {
    title: "Ente mit Orangensauce",
    image: "images/ente-orangensauce.jpeg",
    type: "meat",
    constraints: ["oven", "seasonal"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Entenbrust: "800g",
      Orangen: "4 Stück",
      Honig: "60ml",
      Rotwein: "200ml",
      Kartoffeln: "600g",
      Gemüse: "400g",
    },
  },

  {
    title: "Eriträische Platte",
    image: "images/eritraeische-platte.jpeg",
    type: "meat",
    constraints: ["grain", "beans_lentils"],
    region: "african",
    approved: "False",
    ingredients: {
      "Fleisch gemischt": "800g",
      "Injera Brot": "6 Stück",
      Linsen: "300g",
      "Berbere Gewürz": "30g",
      Zwiebeln: "3 Stück",
      Knoblauch: "6 Zehen",
    },
  },

  {
    title: "Fisch mit Kartoffeln und Paprika",
    image: "images/fisch-kartoffeln-paprika.jpeg",
    type: "meat",
    constraints: ["oven", "seasonal"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Fischfilet: "600g",
      Kartoffeln: "800g",
      Paprika: "400g",
      Olivenöl: "60ml",
      Zitrone: "2 Stück",
      Kräuter: "30g",
    },
  },

  {
    title: "Fisch Taco",
    image: "images/fisch-taco.jpeg",
    type: "meat",
    constraints: ["grain", "salad"],
    region: "latin_american",
    approved: "False",
    ingredients: {
      Fischfilet: "600g",
      "Taco-Schalen": "8 Stück",
      Krautsalat: "300g",
      Avocado: "2 Stück",
      Limetten: "4 Stück",
      Koriander: "30g",
    },
  },

  {
    title: "Fusilli mit Rucola, Salsiccia und Tomaten",
    image: "images/fussili-ruccula-salsiccia-tomaten.jpeg",
    type: "meat",
    constraints: ["pasta", "green_vegetable"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Fusilli: "500g",
      Salsiccia: "400g",
      Rucola: "200g",
      Tomaten: "500g",
      Parmesan: "100g",
      Olivenöl: "60ml",
    },
  },

  {
    title: "Gulasch mit Kroketten",
    image: "images/gulasch-kroketten.jpeg",
    type: "meat",
    constraints: ["oven"],
    region: "eastern_european",
    approved: "False",
    ingredients: {
      Rindfleisch: "800g",
      Kroketten: "600g",
      Zwiebeln: "3 Stück",
      Paprika: "400g",
      Tomatenmark: "100g",
      Rinderbrühe: "500ml",
    },
  },

  {
    title: "Hackbraten mit Kartoffelbrei",
    image: "images/hackbraten-kartoffelbrei.jpeg",
    type: "meat",
    constraints: ["oven", "dairy"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Hackfleisch: "800g",
      Kartoffeln: "800g",
      Milch: "300ml",
      Butter: "100g",
      Zwiebeln: "2 Stück",
      Eier: "2 Stück",
    },
  },

  {
    title: "Hackfleisch mit Lauch und Reis",
    image: "images/hackfleisch-lauch-reis.jpeg",
    type: "meat",
    constraints: ["grain", "green_vegetable"],
    region: "east_asian",
    approved: "False",
    ingredients: {
      Hackfleisch: "600g",
      Reis: "300g",
      Lauch: "400g",
      Sojasoße: "60ml",
      Ingwer: "20g",
      Knoblauch: "4 Zehen",
    },
  },

  {
    title: "Köttbullar mit Kartoffelpüree und Erbsen",
    image: "images/koetbullar-kartoffelpuerree-erbsen.jpeg",
    type: "meat",
    constraints: ["dairy", "green_vegetable"],
    region: "scandinavian",
    approved: "False",
    ingredients: {
      Hackfleisch: "600g",
      Kartoffeln: "800g",
      Erbsen: "300g",
      Sahne: "200ml",
      Butter: "80g",
      Preiselbeeren: "100g",
    },
  },

  {
    title: "Lamm mit Spargel und Kartoffeln",
    image: "images/lamm-spagel-kartoffel.jpeg",
    type: "meat",
    constraints: ["oven", "green_vegetable", "seasonal"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Lammkeule: "800g",
      Spargel: "600g",
      Kartoffeln: "600g",
      Olivenöl: "60ml",
      Rosmarin: "20g",
      Knoblauch: "6 Zehen",
    },
  },

  {
    title: "Lasagne mit Salat",
    image: "images/lasagne-salat.jpeg",
    type: "meat",
    constraints: ["pasta", "oven", "dairy", "salad"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Lasagneplatten: "500g",
      Hackfleisch: "600g",
      Béchamelsoße: "500ml",
      Tomatensoße: "400ml",
      Mozzarella: "300g",
      "Salat gemischt": "200g",
    },
  },

  {
    title: "Maultaschen mit Kartoffelsalat",
    image: "images/maultaschen-kartoffelsalat.jpeg",
    type: "meat",
    constraints: ["pasta", "salad"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Maultaschen: "800g",
      Kartoffeln: "800g",
      Zwiebeln: "2 Stück",
      Essig: "60ml",
      Öl: "80ml",
      Speck: "150g",
    },
  },

  {
    title: "Mexikanischer Teller",
    image: "images/mexikanischer-teller.jpeg",
    type: "meat",
    constraints: ["grain", "beans_lentils", "dairy"],
    region: "latin_american",
    approved: "False",
    ingredients: {
      Hackfleisch: "600g",
      Reis: "300g",
      Bohnen: "400g",
      Käse: "200g",
      Tortillas: "6 Stück",
      Avocado: "2 Stück",
    },
  },

  {
    title: "Penne Bolognese",
    image: "images/penne-bolognese.jpeg",
    type: "meat",
    constraints: ["pasta"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Penne: "500g",
      Hackfleisch: "600g",
      Tomatensoße: "500ml",
      Zwiebeln: "2 Stück",
      Karotten: "200g",
      Sellerie: "200g",
    },
  },

  {
    title: "Pfannen-Lachs mit Gemüse",
    image: "images/pfannen-lachs-gemuese.jpeg",
    type: "meat",
    constraints: ["green_vegetable", "seasonal"],
    region: "scandinavian",
    approved: "False",
    ingredients: {
      Lachsfilet: "800g",
      "Gemüse gemischt": "600g",
      Olivenöl: "60ml",
      Zitrone: "2 Stück",
      Dill: "30g",
      Knoblauch: "4 Zehen",
    },
  },

  {
    title: "Pizza mit Fleischbällchen",
    image: "images/pizza-mit-fleischbaellchen.jpeg",
    type: "meat",
    constraints: ["grain", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Pizzateig: "400g",
      Fleischbällchen: "500g",
      Tomatensoße: "300ml",
      Mozzarella: "300g",
      Basilikum: "20g",
      Olivenöl: "40ml",
    },
  },

  {
    title: "Reisnudeln mit Rinderfilet-Streifen",
    image: "images/reisnudeln-rinderfilet-streifen.jpeg",
    type: "meat",
    constraints: ["pasta", "green_vegetable"],
    region: "east_asian",
    approved: "False",
    ingredients: {
      Reisnudeln: "400g",
      Rinderfilet: "600g",
      "Gemüse gemischt": "500g",
      Sojasoße: "80ml",
      Sesamöl: "40ml",
      Ingwer: "30g",
    },
  },

  {
    title: "Rindsstreifen mit Brokkoli aus dem Wok",
    image: "images/rindsstreifen-brokkoli-wok.jpeg",
    type: "meat",
    constraints: ["green_vegetable", "grain"],
    region: "east_asian",
    approved: "False",
    ingredients: {
      Rindsstreifen: "600g",
      Brokkoli: "600g",
      Reis: "300g",
      Sojasoße: "80ml",
      Knoblauch: "4 Zehen",
      Ingwer: "20g",
    },
  },

  {
    title: "Sauerbraten mit Knödel",
    image: "images/sauerbraten-knoedel.jpeg",
    type: "meat",
    constraints: ["oven", "grain"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Sauerbraten: "1000g",
      Knödel: "8 Stück",
      Rotkohl: "600g",
      Rotweinessig: "200ml",
      Zwiebeln: "3 Stück",
      Lebkuchen: "100g",
    },
  },

  {
    title: "Schnitzel mit Spätzle und Steckrüben",
    image: "images/schnitzel-spaetzle-steckrueben.jpeg",
    type: "meat",
    constraints: ["pasta", "seasonal"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Schweineschnitzel: "800g",
      Spätzle: "400g",
      Steckrüben: "600g",
      Paniermehl: "150g",
      Eier: "3 Stück",
      Butter: "100g",
    },
  },

  {
    title: "Spargel mit Bohnengemüse und Polenta",
    image: "images/spagel-bohnengemuese-polenta.jpeg",
    type: "meat",
    constraints: ["green_vegetable", "seasonal", "grain"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Spargel: "800g",
      "Grüne Bohnen": "400g",
      Polenta: "300g",
      Schinken: "300g",
      Butter: "80g",
      Parmesan: "100g",
    },
  },

  {
    title: "Spaghetti Carbonara",
    image: "images/spagetti-carbonara.jpeg",
    type: "meat",
    constraints: ["pasta", "eggs", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Spaghetti: "500g",
      Speck: "200g",
      Eier: "4 Stück",
      Parmesan: "150g",
      "Schwarzer Pfeffer": "10g",
      Olivenöl: "40ml",
    },
  },

  {
    title: "Steak Bowl",
    image: "images/steak-bowl.jpeg",
    type: "meat",
    constraints: ["grain", "salad"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Rindersteak: "800g",
      Reis: "300g",
      "Salat gemischt": "300g",
      Avocado: "2 Stück",
      Tomaten: "300g",
      Mais: "200g",
    },
  },
];

const vegetarianMeals = [
  // Mediterranean/Italian
  {
    title: "Eggplant Parmigiana with arugula salad",
    image: "old_images/turkish-stuffed-eggplant.jpg",
    type: "vegetarian",
    constraints: ["oven", "dairy", "green_vegetable"],
    region: "mediterranean",
    ingredients: {
      Eggplants: "1000g",
      "Mozzarella cheese": "400g",
      "Parmesan cheese": "200g",
      "Tomato sauce": "600ml",
      Arugula: "200g",
      Basil: "30g",
      "Olive oil": "100ml",
      Breadcrumbs: "150g",
    },
  },

  {
    title: "Tofu-Bowl mit Brokkoli, Reis und Karottensalat",
    image: "images/tofu-bowl-mit-brokkoli-reis-und-karottensalat.jpg",
    type: "vegetarian",
    constraints: ["green_vegetable", "grain", "salad", "dairy"],
    region: "south_east_asian",
    approved: "True",
    ingredients: {
      "Tofu mit süß-scharfer Grillmarinade": "400g",
      Jasminreis: "300g",
      "Brokkoli-Köpfe": "2 Stück",
      Karotten: "2 Stück",
      Limetten: "2 Stück",
      Knoblauchzehen: "4 Stück",
      Erdnussbutter: "100g",
      Sojasoße: "50ml",
      Kokosmilch: "300ml",
      "Sweet-Chili-Sauce": "50g",
    },
  },
  {
    title: "Glasierter Tofu mit Paprika, Gemüse, Reis und Orangensauce",
    image:
      "images/glasierter-tofu-mit-paprika-gemuese-reis-und-orangensauce.jpg",
    type: "vegetarian",
    constraints: ["grain"],
    region: "south_east_asian",
    approved: "True",
    ingredients: {
      Basmatireis: "300g",
      Orangen: "4 Stück",
      Sojasoße: "100ml",
      "Rote Paprika": "4 Stück",
      Knoblauchzehen: "4 Stück",
      Tofu: "400g",
      Frühlingszwiebelstangen: "4 Stück",
      Kokosraspeln: "2 Handvoll",
    },
  },
  {
    title: "Spinat-Salat mit gebackenem Hirtenkäse und Kichererbsen",
    image:
      "images/spinat-salat-mit-gebackenem-hirtenkaese-und-kichererbsen.jpg",
    type: "vegetarian",
    constraints: [
      "green_vegetable",
      "oven",
      "grain",
      "salad",
      "dairy",
      "beans_lentils",
    ],
    region: "mediterranean",
    approved: "True",
    ingredients: {
      "Baby-Spinat": "200g",
      "Petersilie (glatt, Büschel)": "1 kleines Büschel",
      Kichererbsen: "800g",
      "Salatgurke (groß)": "1 Stück",
      "Ciabatta-Brote (klein)": "2 Stück",
      Frühlingszwiebelstangen: "2 Stück",
      Hirtenkäse: "400g",
    },
  },
  {
    title: "Gnocchi-Pfanne mit Spinat und Sonnenblumenkernen",
    image: "images/gnocchi-pfanne-mit-spinat-und-sonnenblumenkernen.jpg",
    type: "vegetarian",
    constraints: ["green_vegetable", "grain", "salad", "dairy"],
    region: "mediterranean",
    approved: "True",
    ingredients: {
      Gnocchi: "1000g",
      "Baby-Spinat": "200g",
      Knoblauchzehen: "4 Stück",
      "Creme Fraîche": "200ml",
      "Parmesan (geraspelt)": "50g",
      "Gouda (geraspelt)": "100g",
      "Basilikum-Pesto": "30ml",
      Sonnenblumenkerne: "50g",
    },
  },
  {
    title: "Spaghetti al Limone mit Brokkoli und Panko-Bröseln",
    image: "images/spaghetti-al-limone-mit-brokkoli-und-panko-broeseln.jpg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "grain", "dairy"],
    region: "mediterranean",
    approved: "True",
    ingredients: {
      Spaghetti: "500g",
      "Brokkoli-Köpfe": "2 Stück",
      "Parmesan (gerieben)": "50g",
      Sahne: "300g",
      Knoblauchzehen: "2 Stück",
      Zitronen: "2 Stück",
      "Parmesan (geraspelt)": "100g",
      Semmelbrösel: "100g",
      "Weiße Zwiebeln": "2 Stück",
    },
  },
  {
    title: "Sandwich-Baguette mit Crunchy Champignons und Salat",
    image: "images/sandwich-baguette-mit-crunchy-champignons-und-salat.jpg",
    type: "vegetarian",
    constraints: ["green_vegetable", "oven", "grain", "salad", "dairy"],
    region: "north_american",
    approved: "True",
    ingredients: {
      "Steinofen-Baguette": "2 Stück",
      "Romana-Salat-Herzen": "2 Stück",
      "Tomaten (groß)": "2 Stück",
      Joghurt: "200g",
      Karotten: "2 Stück",
      Frühlingszwiebelstangen: "2 Stück",
      "Panko-Mehl": "50g",
      "Parmesan (gerieben)": "50g",
      Champignons: "400g",
    },
  },
  {
    title: "Grill-Käse Tacos mit Gurke und Rucola",
    image: "images/grill-kaese-tacos-mit-gurke-und-rucola.jpg",
    type: "vegetarian",
    constraints: ["green_vegetable", "dairy", "grain", "salad"],
    region: "latin_american",
    approved: "True",
    ingredients: {
      "Weizen-Tortillas": "12 Stück",
      Grillkäse: "400g",
      Rucola: "100g",
      "Rote Chilischote": "1 Stück",
      "Rote Zwiebeln": "4 Stück",
      Knoblauchzehen: "2 Stück",
      Gurken: "2 Stück",
      Zitrone: "1 Stück",
    },
  },
  {
    title: "Geschnetzeltes mit Kartoffel-Stampf, Schmor-Tomaten und Bohnen",
    image:
      "images/geschnetzeltes-mit-kartoffel-stampf-schmor-tomaten-und-bohnen.jpg",
    type: "vegetarian",
    constraints: ["green_vegetable", "dairy"],
    region: "germanic",
    approved: "True",
    ingredients: {
      "Mehligkochende Kartoffeln": "800g",
      Zwiebeln: "2 Stück",
      "Grüne Stangenbohnen": "300g",
      Knoblauchzehen: "2 Stück",
      "Cocktailtomaten (Büschel)": "2 Büschel",
      Frühlingszwiebelstangen: "4 Stück",
      Sahne: "300ml",
      "Geschnetzeltes (vegetarisch)": "300g",
    },
  },

  // New vegetarian dishes from new_images folder
  {
    title: "Apfelcrumble mit Eis und Karamell",
    image: "images/apfelcrumble-eis-karamell.jpeg",
    type: "vegetarian",
    constraints: ["dairy", "seasonal"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Äpfel: "800g",
      Haferflocken: "200g",
      Butter: "120g",
      Zucker: "100g",
      Vanilleeis: "400g",
      Karamellsauce: "150ml",
    },
  },

  {
    title: "Apfelstrudel mit Vanilleeis und Sahne",
    image: "images/apfelstrudel-vanilleeis-sahne.jpeg",
    type: "vegetarian",
    constraints: ["oven", "dairy", "seasonal"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Strudelteig: "400g",
      Äpfel: "800g",
      Rosinen: "100g",
      Zimt: "10g",
      Vanilleeis: "400g",
      Sahne: "200ml",
    },
  },

  {
    title: "Bagel mit Frischkäse",
    image: "images/bagel-frischkaese.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Bagel: "4 Stück",
      Frischkäse: "300g",
      "Lachs (optional)": "200g",
      Kapern: "50g",
      "Rote Zwiebeln": "1 Stück",
      Dill: "20g",
    },
  },

  {
    title: "Bananenbrot",
    image: "images/bananenbrot.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy", "eggs"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Bananen: "500g",
      Mehl: "300g",
      Butter: "100g",
      Zucker: "150g",
      Eier: "2 Stück",
      Backpulver: "10g",
    },
  },

  {
    title: "Blueberry Pancakes",
    image: "images/blueberry-pancakes.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy", "eggs"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Mehl: "300g",
      Blaubeeren: "300g",
      Milch: "400ml",
      Eier: "3 Stück",
      Butter: "100g",
      Ahornsirup: "200ml",
    },
  },

  {
    title: "Bohnen mit Guacamole und Reis",
    image: "images/bohnen-guacamole-reis.jpeg",
    type: "vegetarian",
    constraints: ["beans_lentils", "grain", "salad"],
    region: "latin_american",
    approved: "False",
    ingredients: {
      "Schwarze Bohnen": "600g",
      Reis: "300g",
      Avocados: "4 Stück",
      Limetten: "3 Stück",
      Tomaten: "300g",
      Koriander: "30g",
    },
  },

  {
    title: "Brokkoli-Pilz-Farfalle",
    image: "images/brokkoli-pilz-farfalle.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Farfalle: "500g",
      Brokkoli: "600g",
      Pilze: "400g",
      Sahne: "300ml",
      Parmesan: "100g",
      Knoblauch: "4 Zehen",
    },
  },

  {
    title: "Chocolate Lava Cake mit Eis",
    image: "images/chocklate-lava-cake-eis.jpeg",
    type: "vegetarian",
    constraints: ["oven", "dairy", "eggs"],
    region: "north_american",
    approved: "False",
    ingredients: {
      "Dunkle Schokolade": "200g",
      Butter: "150g",
      Eier: "4 Stück",
      Zucker: "120g",
      Mehl: "80g",
      Vanilleeis: "400g",
    },
  },

  {
    title: "Conchiglie in Pilzrahmensauce",
    image: "images/conchiglie-pilzrahmen.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Conchiglie: "500g",
      "Pilze gemischt": "600g",
      Sahne: "400ml",
      Weißwein: "200ml",
      Zwiebeln: "2 Stück",
      Petersilie: "30g",
    },
  },

  {
    title: "Fritierte Stangenbohnen mit Dip",
    image: "images/fritierte-stangenbohnen-dip.jpeg",
    type: "vegetarian",
    constraints: ["green_vegetable", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      "Grüne Bohnen": "600g",
      Paniermehl: "200g",
      Eier: "3 Stück",
      Joghurt: "300ml",
      Knoblauch: "3 Zehen",
      Zitrone: "2 Stück",
    },
  },

  {
    title: "Fusilli mit TK-Rahmspinat",
    image: "images/fussili-tk-rahmspinat.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Fusilli: "500g",
      Rahmspinat: "600g",
      Sahne: "200ml",
      Parmesan: "100g",
      Pinienkerne: "80g",
      Knoblauch: "3 Zehen",
    },
  },

  {
    title: "Gebratene Maultaschen mit Erbsen und Karotten",
    image: "images/gebratene-maultaschen-erbsen-karotten.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "eggs"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Maultaschen: "800g",
      Erbsen: "300g",
      Karotten: "400g",
      Eier: "4 Stück",
      Zwiebeln: "2 Stück",
      Butter: "80g",
    },
  },

  {
    title: "Glasnudeln mit Mini-Mais aus dem Wok",
    image: "images/glasnudeln-mini-mais-wok.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable"],
    region: "east_asian",
    approved: "False",
    ingredients: {
      Glasnudeln: "400g",
      "Mini-Mais": "300g",
      "Pak Choi": "400g",
      Sojasoße: "80ml",
      Sesamöl: "60ml",
      Ingwer: "30g",
    },
  },

  {
    title: "Gnocchi mit Käsesauce",
    image: "images/gnocci-kaesesauce.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Gnocchi: "800g",
      Gouda: "200g",
      Sahne: "300ml",
      Parmesan: "100g",
      Butter: "60g",
      Muskatnuss: "5g",
    },
  },

  {
    title: "Gnocchi mit Pfannengemüse",
    image: "images/gnocci-pfannengemuese.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Gnocchi: "800g",
      Zucchini: "400g",
      Paprika: "300g",
      Tomaten: "400g",
      Mozzarella: "200g",
      Basilikum: "30g",
    },
  },

  {
    title: "Gyoza mit Brokkoli und Quinoa",
    image: "images/gyoza-brokkoli-quinoa.jpeg",
    type: "vegetarian",
    constraints: ["grain", "green_vegetable"],
    region: "east_asian",
    approved: "False",
    ingredients: {
      Gyoza: "20 Stück",
      Quinoa: "300g",
      Brokkoli: "600g",
      Sojasoße: "80ml",
      Sesamöl: "40ml",
      Ingwer: "20g",
    },
  },

  {
    title: "Halloumi mit Süßkartoffeln und Linsen",
    image: "images/halloumi-suesskartoffel-linsen.jpeg",
    type: "vegetarian",
    constraints: ["dairy", "beans_lentils", "seasonal"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Halloumi: "400g",
      Süßkartoffeln: "800g",
      "Rote Linsen": "300g",
      Spinat: "300g",
      Olivenöl: "80ml",
      Zitrone: "2 Stück",
    },
  },

  {
    title: "Indianisches Fladenbrot mit Bohnenmuss",
    image: "images/indianische-fladenbrot-mit-bohnenmuss.jpeg",
    type: "vegetarian",
    constraints: ["grain", "beans_lentils"],
    region: "south_east_asian",
    approved: "False",
    ingredients: {
      "Naan Brot": "8 Stück",
      "Schwarze Bohnen": "600g",
      Zwiebeln: "3 Stück",
      Kreuzkümmel: "15g",
      Koriander: "30g",
      Limetten: "3 Stück",
    },
  },

  {
    title: "Käsespätzle mit Salat",
    image: "images/kaesespaetzle-Salat.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy", "salad"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Spätzle: "600g",
      Emmentaler: "300g",
      Zwiebeln: "3 Stück",
      "Salat gemischt": "300g",
      Butter: "100g",
      Röstzwiebeln: "80g",
    },
  },

  {
    title: "Kaiserschmarr",
    image: "images/kaiserschmarn.jpeg",
    type: "vegetarian",
    constraints: ["eggs", "dairy", "seasonal"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Eier: "6 Stück",
      Mehl: "200g",
      Milch: "400ml",
      Zucker: "80g",
      Butter: "100g",
      Zwetschgenröster: "300ml",
    },
  },

  {
    title: "Kichererbsen-Curry mit Blumenkohl",
    image: "images/kichererbsen-curry-blumenkohl.jpeg",
    type: "vegetarian",
    constraints: ["beans_lentils", "seasonal", "grain"],
    region: "south_east_asian",
    approved: "False",
    ingredients: {
      Kichererbsen: "600g",
      Blumenkohl: "800g",
      Basmatireis: "300g",
      Kokosmilch: "400ml",
      "Curry Pulver": "30g",
      Ingwer: "40g",
    },
  },

  {
    title: "Mac'n'Cheese",
    image: "images/mac'n'cheese.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Makkaroni: "500g",
      Cheddar: "400g",
      Milch: "500ml",
      Butter: "100g",
      Mehl: "60g",
      Paniermehl: "100g",
    },
  },

  {
    title: "Makkaroni mit Paprikasauce und Mozzarella",
    image: "images/maccaroni-paprikasauce-mozzarella.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy", "oven"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Makkaroni: "500g",
      Paprika: "600g",
      Mozzarella: "300g",
      Tomaten: "400g",
      Basilikum: "30g",
      Olivenöl: "80ml",
    },
  },

  {
    title: "Mini Penne mit Zucchini und Karotten",
    image: "images/mini-penne-Zucchini-Karotte.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      "Mini Penne": "500g",
      Zucchini: "400g",
      Karotten: "300g",
      Parmesan: "100g",
      Olivenöl: "60ml",
      Knoblauch: "3 Zehen",
    },
  },

  {
    title: "Nudeln mit Zitronensauce",
    image: "images/nudeln-zitronensauce.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Tagliatelle: "500g",
      Zitronen: "4 Stück",
      Sahne: "300ml",
      Parmesan: "150g",
      Butter: "80g",
      Petersilie: "40g",
    },
  },

  {
    title: "Ofengemüse mit Käse",
    image: "images/ofengemuese-kaese.jpeg",
    type: "vegetarian",
    constraints: ["oven", "dairy", "seasonal"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      "Gemüse gemischt": "1000g",
      Feta: "200g",
      Mozzarella: "200g",
      Olivenöl: "80ml",
      Kräuter: "40g",
      Knoblauch: "4 Zehen",
    },
  },

  {
    title: "Omlett mit Pilzen",
    image: "images/omlet-pilze.jpeg",
    type: "vegetarian",
    constraints: ["eggs", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Eier: "8 Stück",
      Champignons: "400g",
      Käse: "200g",
      Butter: "80g",
      Schnittlauch: "30g",
      Milch: "100ml",
    },
  },

  {
    title: "Pancakes mit Himbeeren und Mascarpone",
    image: "images/pancakes-himbeer-mascapone.jpeg",
    type: "vegetarian",
    constraints: ["grain", "eggs", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Mehl: "300g",
      Himbeeren: "400g",
      Mascarpone: "250g",
      Eier: "3 Stück",
      Milch: "400ml",
      Ahornsirup: "200ml",
    },
  },

  {
    title: "Pesto Schnecken",
    image: "images/pesto-schnecken.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy", "oven"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Blätterteig: "400g",
      Pesto: "150g",
      Parmesan: "100g",
      Mozzarella: "200g",
      Pinienkerne: "80g",
      Basilikum: "30g",
    },
  },

  {
    title: "Porridge mit Bananen und Cornflakes",
    image: "images/porridge-bananen-cornflakes.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy"],
    region: "scandinavian",
    approved: "False",
    ingredients: {
      Haferflocken: "200g",
      Bananen: "4 Stück",
      Cornflakes: "100g",
      Milch: "600ml",
      Honig: "80ml",
      Zimt: "5g",
    },
  },

  {
    title: "Quinoa mit Kichererbsen, Paprika und Halloumi",
    image: "images/quinoa-kichererbsen-paprika-halloumi.jpeg",
    type: "vegetarian",
    constraints: ["grain", "beans_lentils", "dairy", "salad"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Quinoa: "300g",
      Kichererbsen: "600g",
      Paprika: "400g",
      Halloumi: "300g",
      Rucola: "200g",
      Olivenöl: "80ml",
    },
  },

  {
    title: "Rahmensuppe",
    image: "images/rahmensuppe.jpeg",
    type: "vegetarian",
    constraints: ["dairy", "grain"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Gemüsebrühe: "1000ml",
      Sahne: "300ml",
      Kartoffeln: "400g",
      Karotten: "200g",
      Brot: "8 Scheiben",
      Petersilie: "30g",
    },
  },

  {
    title: "Riesenfusilli mit Burrata und Pesto",
    image: "images/riesenfussili-burrata-pesto.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Riesenfusilli: "500g",
      Burrata: "400g",
      Pesto: "150g",
      Cherrytomaten: "300g",
      Rucola: "150g",
      Pinienkerne: "80g",
    },
  },

  {
    title: "Risotto mit Pilzen",
    image: "images/risotto-pilze.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      "Arborio Reis": "400g",
      "Pilze gemischt": "600g",
      Parmesan: "150g",
      Weißwein: "200ml",
      Gemüsebrühe: "1000ml",
      Butter: "100g",
    },
  },

  {
    title: "Röstbaguette mit Pilzen",
    image: "images/roestbaguette-pilze.jpeg",
    type: "vegetarian",
    constraints: ["grain", "dairy"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Baguette: "2 Stück",
      Champignons: "500g",
      Knoblauch: "4 Zehen",
      Käse: "200g",
      Butter: "80g",
      Petersilie: "30g",
    },
  },

  {
    title: "Rührei mit Crispy Bacon",
    image: "images/ruehrei-crispy-balcon.jpeg",
    type: "vegetarian",
    constraints: ["eggs", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Eier: "8 Stück",
      "Speck (vegetarisch)": "200g",
      Butter: "60g",
      Schnittlauch: "30g",
      Milch: "100ml",
      Toast: "8 Scheiben",
    },
  },

  {
    title: "Schwarzwälder Kirschtorte",
    image: "images/schwarzwaelderkischtorte.jpeg",
    type: "vegetarian",
    constraints: ["dairy", "eggs", "seasonal"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Biskuitboden: "1 Stück",
      Kirschen: "600g",
      Sahne: "600ml",
      Schokolade: "200g",
      Kirschlikör: "100ml",
      Zucker: "150g",
    },
  },

  {
    title: "Shakshuka",
    image: "images/shakshuka.jpeg",
    type: "vegetarian",
    constraints: ["eggs", "dairy"],
    region: "middle_eastern",
    approved: "False",
    ingredients: {
      Eier: "6 Stück",
      Tomaten: "800g",
      Paprika: "300g",
      Feta: "200g",
      Zwiebeln: "2 Stück",
      Harissa: "30g",
    },
  },

  {
    title: "Smashed Potato Salat",
    image: "images/smashedpotato-salat.jpeg",
    type: "vegetarian",
    constraints: ["oven", "salad", "dairy"],
    region: "scandinavian",
    approved: "False",
    ingredients: {
      "Kleine Kartoffeln": "1000g",
      "Salat gemischt": "300g",
      Joghurt: "200ml",
      Dill: "40g",
      Olivenöl: "80ml",
      Zitrone: "2 Stück",
    },
  },

  {
    title: "Spätzle mit Linsen",
    image: "images/spaetzle-mit-linsen.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "beans_lentils"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Spätzle: "600g",
      Berglinsen: "400g",
      Zwiebeln: "3 Stück",
      "Speck (vegetarisch)": "150g",
      Gemüsebrühe: "800ml",
      Essig: "60ml",
    },
  },

  {
    title: "Spätzle mit Pilzen",
    image: "images/spaetzle-pilze.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "dairy"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Spätzle: "600g",
      "Pilze gemischt": "600g",
      Sahne: "300ml",
      Zwiebeln: "2 Stück",
      Petersilie: "40g",
      Butter: "80g",
    },
  },

  {
    title: "Spaghetti mit Gartentomaten",
    image: "images/spagetti-gartentomaten.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "seasonal"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Spaghetti: "500g",
      Tomaten: "800g",
      Basilikum: "40g",
      Knoblauch: "4 Zehen",
      Olivenöl: "100ml",
      Parmesan: "100g",
    },
  },

  {
    title: "Spaghetti mit Onkel Martins Tomatensauce",
    image: "images/spagetti-onkelmartins-tomatensauce.jpeg",
    type: "vegetarian",
    constraints: ["pasta"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Spaghetti: "500g",
      Tomatensoße: "600ml",
      Zwiebeln: "2 Stück",
      Knoblauch: "4 Zehen",
      Basilikum: "30g",
      Olivenöl: "80ml",
    },
  },

  {
    title: "Spinatsalat mit Gorgonzola-Krümeln",
    image: "images/spinatsalat-gorgonzola-kruemel.jpeg",
    type: "vegetarian",
    constraints: ["salad", "dairy", "green_vegetable"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Spinat: "400g",
      Gorgonzola: "200g",
      Walnüsse: "100g",
      Birnen: "3 Stück",
      Balsamico: "80ml",
      Olivenöl: "80ml",
    },
  },

  {
    title: "Spirellis mit Lauch-Schmand-Gemüse",
    image: "images/spirellis-lauch-schmand-gemuese.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable", "dairy"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Spirellis: "500g",
      Lauch: "600g",
      Schmand: "300ml",
      Erbsen: "300g",
      Möhren: "200g",
      Dill: "30g",
    },
  },

  {
    title: "Tomaten-Feigensalat mit Burrata und Baguette",
    image: "images/tomaten-feigensalat-burrata-baguette.jpeg",
    type: "vegetarian",
    constraints: ["salad", "dairy", "grain", "seasonal"],
    region: "mediterranean",
    approved: "False",
    ingredients: {
      Tomaten: "600g",
      Feigen: "6 Stück",
      Burrata: "300g",
      Baguette: "1 Stück",
      Rucola: "150g",
      Balsamico: "80ml",
    },
  },

  {
    title: "Überbackene Kartoffeln mit Rosenkohl",
    image: "images/ueberbacken-kartoffel-rosenkohl.jpeg",
    type: "vegetarian",
    constraints: ["oven", "dairy", "green_vegetable", "seasonal"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Kartoffeln: "1000g",
      Rosenkohl: "600g",
      Käse: "300g",
      Sahne: "300ml",
      "Speck (vegetarisch)": "150g",
      Zwiebeln: "2 Stück",
    },
  },

  {
    title: "Waffeln mit Obst",
    image: "images/waffeln-mit-obst.jpeg",
    type: "vegetarian",
    constraints: ["grain", "eggs", "dairy"],
    region: "north_american",
    approved: "False",
    ingredients: {
      Mehl: "300g",
      Eier: "4 Stück",
      Milch: "400ml",
      Butter: "100g",
      "Beeren gemischt": "500g",
      Ahornsirup: "200ml",
    },
  },

  {
    title: "Schupfnudeln mit Zucchini und Karotten",
    image: "images/schupfnudeln-zucchini-karotten.jpeg",
    type: "vegetarian",
    constraints: ["pasta", "green_vegetable"],
    region: "germanic",
    approved: "False",
    ingredients: {
      Schupfnudeln: "600g",
      Zucchini: "400g",
      Karotten: "300g",
      Zwiebeln: "2 Stück",
      Petersilie: "30g",
      Butter: "80g",
    },
  },
];
